name: Build IATA → City map

on:
  workflow_dispatch:
  schedule:
    - cron: "15 3 * * 1"  # 매주 월요일 03:15 UTC (원하면 삭제)

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # TLS 오류 대비: 먼저 정상 다운로드 시도 → 실패 시 --insecure 로 재시도
      - name: Download airports.csv (robust TLS)
        run: |
          set -e
          URL="https://ourairports.com/data/airports.csv"
          echo "Downloading $URL"
          if ! curl -fsSL --retry 5 --retry-delay 5 "$URL" -o airports.csv; then
            echo "Primary download failed → retry with --insecure"
            curl -fsSLk --retry 5 --retry-delay 5 "$URL" -o airports.csv
          fi
          # 간단 검증: 파일 존재/사이즈 + 헤더에 iata_code 포함 여부
          test -s airports.csv
          head -n1 airports.csv | grep -qi 'iata_code' || { echo "Invalid CSV header"; exit 1; }
          wc -c airports.csv

      - name: Build iata-city.json
        env:
          CSV_PATH: airports.csv   # 스크립트가 이 로컬 파일을 우선 사용
        run: |
          node scripts/build-iata-city.js
          test -f public/data/iata-city.json

      - name: Commit & push changes (force add)
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f public/data/iata-city.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: refresh iata-city.json [skip ci]"
            git push
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: iata-city.json
          path: public/data/iata-city.json
