name: Build IATA → City map

on:
  workflow_dispatch:
  schedule:
    - cron: '17 3 * * 1'  # 매주 월요일 03:17 UTC 자동 갱신

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download airports.csv (with fallback)
        run: |
          set -euo pipefail
          CSV="$RUNNER_TEMP/airports.csv"

          echo "→ Try primary (ourairports.com)"
          curl -LfsS https://ourairports.com/data/airports.csv -o "$CSV" || true

          if [ ! -s "$CSV" ]; then
            echo "→ Primary failed, try mirror (GitHub)"
            curl -LfsS https://raw.githubusercontent.com/davidmegginson/ourairports-data/master/airports.csv -o "$CSV" || true
          fi

          if [ ! -s "$CSV" ]; then
            echo "✗ All downloads failed" >&2
            exit 1
          fi

          echo "✓ CSV size:"; wc -c "$CSV"

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build iata-city.json
        env:
          AIRPORTS_CSV_PATH: ${{ runner.temp }}/airports.csv  # ← 스크립트가 이 로컬 파일을 읽습니다
        run: node scripts/build-iata-city.js

      - name: Commit & push changes (if any)
        run: |
          set -e
          if git status --porcelain | grep -q "public/data/iata-city.json"; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add public/data/iata-city.json
            git commit -m "chore: refresh iata-city.json [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi

      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: iata-city.json
          path: public/data/iata-city.json
