name: Build IATA → City map

on:
  workflow_dispatch: {}
  schedule:
    # 매일 03:15 UTC (한국 12:15/11:15) 자동 갱신
    - cron: "15 3 * * *"
  push:
    paths:
      - "scripts/build-iata-city.js"

permissions:
  contents: write  # 결과 JSON을 커밋하려면 필요

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build iata-city.json
        run: node scripts/build-iata-city.js

      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(data): update iata-city.json"
          file_pattern: public/data/iata-city.json
