name: Build IATA → City map

on:
  workflow_dispatch:
  schedule:
    - cron: "15 3 * * 1"  # 매주 월요일 03:15 UTC (원하면 삭제)

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # 네트워크 TLS 이슈 회피: 러너에서 curl로 CSV를 미리 받아서 파일로 사용
      - name: Download airports.csv (via curl)
        run: |
          set -e
          curl -fsSL --retry 5 --retry-delay 5 \
            https://ourairports.com/data/airports.csv \
            -o airports.csv
          echo "Downloaded airports.csv (bytes):"
          wc -c airports.csv

      - name: Build iata-city.json
        env:
          CSV_PATH: airports.csv   # 스크립트가 이 파일을 우선 사용
        run: |
          node scripts/build-iata-city.js
          test -f public/data/iata-city.json

      # .gitignore에 막혀 있어도 강제로 add 해서 커밋/푸시
      - name: Commit & push changes (force add)
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -f public/data/iata-city.json

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: refresh iata-city.json [skip ci]"
            git push
          fi

      # (선택) 결과물 바로 내려받기용 아티팩트
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: iata-city.json
          path: public/data/iata-city.json
